### ISSUE TITLE
Can you introduce the hardware configuration?

### ISSUE THREAD

**Issue by Zeeman206** [vikas08thapa/Obstacle_avoidance_mobile_robot_Microsoft_kinect#1]
Can you introduce the hardware configuration, such as
Raspberry Pi3 / 4?
Kinect V1 / V2?
What display is used to print "You are too close" and other information?

**Comment by vikas08thapa** [comment]
Raspberry Pi3.
Kinect V1.
Display used was the VNC Connect my laptop itself was showing the values.
Watch This page[ https://www.vikasthapa.com/obstacle-avoidance-mobile-robot]
